spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOrigins: '*'
      routes:
        - id: path_route
          # uri: ${service-url.user-service}/user/get/{id}
          uri: lb://user-service
          predicates:
            - Path=/user/get/{id}
            
        - id: userservice_route
          uri: http://localhost:8080
          predicates:
            - Path=/user/test
